name: flutter_project_setup
description: "Una CLI per generare progetti Flutter con architettura selezionata."
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dart_console: ^4.1.1
  # path: ^1.8.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  flutter_project_setup: flutter_project_setup
